import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:share_plus/share_plus.dart';
import '../state/app_state.dart';
import '../engine/pdf_generator.dart';
import '../utils/formatters.dart';

class RbiDraftScreen extends StatelessWidget {
  const RbiDraftScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final appState = Provider.of<AppProvider>(context);
    final terms = appState.confirmedTerms;
    final result = appState.calculationResult;

    final formatAmt = (double? amt) => amt == null ? '[auto-filled]' : Formatters.formatAmountWithoutSymbol(amt);
    final formatPct = (double? pct) => pct == null ? '[X]' : pct.toStringAsFixed(1).replaceAll(RegExp(r'\.0$'), '');
    final formatMonths = (int? m) => m == null ? '[X]' : m.toString();

    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(title: const Text('रिपोर्ट देखें  (Draft Report)')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Context line
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: const Color(0xFF1E3A8A).withValues(alpha: 0.08),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: const Color(0xFF1E3A8A), width: 1.5),
              ),
              child: const Text(
                'Draft complaint report — review and submit through the official RBI complaint process.',
                style: TextStyle(
                  fontSize: 14,
                  color: Color(0xFF1E3A8A),
                  fontWeight: FontWeight.bold,
                ),
                textAlign: TextAlign.center,
              ),
            ),
            const SizedBox(height: 32),

            // PDF-style document card
            Container(
              decoration: BoxDecoration(
                border: Border.all(color: Colors.black26, width: 1),
                borderRadius: BorderRadius.circular(4),
              ),
              child: Stack(
                children: [
                  // Document content
                  Padding(
                    padding: const EdgeInsets.all(24),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'LOAN TRANSPARENCY REPORT',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                            letterSpacing: 1.5,
                          ),
                        ),
                        const SizedBox(height: 4),
                        Text(
                          'Generated by LoanKaSach - ${DateTime.now().toLocal().toString().split(' ')[0]}',
                          style: const TextStyle(fontSize: 12, color: Colors.black45),
                        ),
                        const Divider(height: 32),
                        _draftRow('Loan Principal', '₹${formatAmt(terms?.principal_amount)}'),
                        _draftRow('Tenure', '${formatMonths(terms?.tenure_months)} months'),
                        _draftRow('Advertised Flat Rate', '${formatPct(terms?.advertised_flat_rate)}% p.a.'),
                        _draftRow('Upfront Processing Fee', '₹${formatAmt(terms?.upfront_processing_fee)}'),
                        _draftRow('Monthly Insurance Premium', '₹${formatAmt(terms?.monthly_insurance_premium)}'),
                        const Divider(height: 32),
                        _draftRow('Calculated Effective Annualized Cost', '${formatPct(result?.true_apr)}%', isHighlighted: true),
                        _draftRow('Total Hidden Cost', '₹${formatAmt(result?.total_hidden_cost)}', isHighlighted: true),
                        const SizedBox(height: 32),
                        const Text(
                          'Cost analysis uses a deterministic cash-flow calculation. RBI KFS guidance requires disclosure of APR and associated charges. Verify the lender\'s KFS and applicable RBI requirements before submitting a complaint.\n\nSource: RBI — Key Facts Statement (KFS) for Loans & Advances, RBI/2024-25/18, April 15, 2024.',
                          style: TextStyle(fontSize: 12, color: Colors.black54),
                        ),
                      ],
                    ),
                  ),

                  // DRAFT watermark
                  Positioned.fill(
                    child: IgnorePointer(
                      child: Center(
                        child: Transform.rotate(
                          angle: -0.5,
                          child: Text(
                            'DRAFT ONLY\nReview before submission',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 32,
                              fontWeight: FontWeight.bold,
                              color: Colors.red.withValues(alpha: 0.12),
                              letterSpacing: 2,
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),

            const SizedBox(height: 32),

            // Share button
            ElevatedButton.icon(
              onPressed: () async {
                if (terms == null || result == null) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text('डेटा नहीं मिला। कृपया पहले लोन की डिटेल्स भरें।')),
                  );
                  return;
                }
                
                try {
                  final pdfBytes = await PDFGenerator.generateEvidenceDocument(
                    terms: terms,
                    result: result,
                  );
                  
                  final xFile = XFile.fromData(pdfBytes, mimeType: 'application/pdf', name: 'CoastReveal_Report.pdf'); await Share.shareXFiles([xFile], subject: 'CoastReveal - Loan Transparency Report', text: 'Please find attached the Loan Transparency Report.');
                } catch (e) {
                  if (context.mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(content: Text('Failed to share document: $e')),
                    );
                  }
                }
              },
              icon: const Icon(Icons.share),
              label: const Text('WhatsApp / Email से भेजें'),
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF25D366), // WhatsApp green
                foregroundColor: Colors.white,
                minimumSize: const Size(double.infinity, 60),
              ),
            ),

            const SizedBox(height: 12),
            ElevatedButton(
              onPressed: () {
                Navigator.popUntil(context, (route) => route.isFirst);
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF1E3A8A),
              ),
              child: const Text('दोबारा शुरू करें  (Start Over)'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _draftRow(String label, String value, {bool isHighlighted = false}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Expanded(
            child: Text(
              label,
              style: TextStyle(
                fontSize: 14,
                fontWeight: isHighlighted ? FontWeight.bold : FontWeight.normal,
                color: isHighlighted ? const Color(0xFFDC2626) : Colors.black87,
              ),
            ),
          ),
          Text(
            value,
            style: TextStyle(
              fontSize: 14,
              fontWeight: isHighlighted ? FontWeight.bold : FontWeight.normal,
              color: isHighlighted ? const Color(0xFFDC2626) : Colors.black87,
            ),
          ),
        ],
      ),
    );
  }
}

