import 'package:flutter/material.dart';

class RbiDraftScreen extends StatelessWidget {
  const RbiDraftScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(title: const Text('RBI Draft Preview')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Context line
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: const Color(0xFF1E3A8A).withValues(alpha: 0.08),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: const Color(0xFF1E3A8A), width: 1.5),
              ),
              child: const Text(
                'Yeh draft RBI Ombudsman ko bhejne yogya hai.\n(This draft is suitable for submission to the RBI Ombudsman.)',
                style: TextStyle(
                  fontSize: 15,
                  color: Color(0xFF1E3A8A),
                  fontWeight: FontWeight.bold,
                ),
                textAlign: TextAlign.center,
              ),
            ),
            const SizedBox(height: 32),

            // PDF-style document card
            Container(
              decoration: BoxDecoration(
                border: Border.all(color: Colors.black26, width: 1),
                borderRadius: BorderRadius.circular(4),
              ),
              child: Stack(
                children: [
                  // Document content
                  Padding(
                    padding: const EdgeInsets.all(24),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'LOAN TRANSPARENCY REPORT',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                            letterSpacing: 1.5,
                          ),
                        ),
                        const SizedBox(height: 4),
                        Text(
                          'Generated by LoanKaSach · ${DateTime.now().toLocal().toString().split(' ')[0]}',
                          style: const TextStyle(fontSize: 12, color: Colors.black45),
                        ),
                        const Divider(height: 32),
                        _draftRow('Loan Principal', '₹[auto-filled]'),
                        _draftRow('Tenure', '[X] months'),
                        _draftRow('Advertised Flat Rate', '[X]% p.a.'),
                        _draftRow('Upfront Processing Fee', '₹[auto-filled]'),
                        _draftRow('Monthly Insurance Premium', '₹[auto-filled]'),
                        const Divider(height: 32),
                        _draftRow('True APR (Calculated)', '[X]%', isHighlighted: true),
                        _draftRow('Total Hidden Cost', '₹[auto-filled]', isHighlighted: true),
                        const SizedBox(height: 32),
                        const Text(
                          'This report was generated using a deterministic IRR calculation per RBI circular RBI/2022-23/74. The lender is obligated to disclose the Annual Percentage Rate (APR) before loan disbursement.',
                          style: TextStyle(fontSize: 12, color: Colors.black54),
                        ),
                      ],
                    ),
                  ),

                  // DRAFT watermark
                  Positioned.fill(
                    child: IgnorePointer(
                      child: Center(
                        child: Transform.rotate(
                          angle: -0.5,
                          child: Text(
                            'DRAFT ONLY',
                            style: TextStyle(
                              fontSize: 56,
                              fontWeight: FontWeight.bold,
                              color: Colors.red.withValues(alpha: 0.12),
                              letterSpacing: 4,
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),

            const SizedBox(height: 32),

            // Share button
            ElevatedButton.icon(
              onPressed: () {
                // TODO: Implement share via WhatsApp/Email
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text('Share via WhatsApp/Email — coming in M3 integration'),
                  ),
                );
              },
              icon: const Icon(Icons.share),
              label: const Text('Share via WhatsApp / Email'),
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF25D366), // WhatsApp green
                foregroundColor: Colors.white,
                minimumSize: const Size(double.infinity, 60),
              ),
            ),

            const SizedBox(height: 12),
            ElevatedButton(
              onPressed: () {
                Navigator.popUntil(context, (route) => route.isFirst);
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF1E3A8A),
              ),
              child: const Text('Start Over'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _draftRow(String label, String value, {bool isHighlighted = false}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(
            label,
            style: TextStyle(
              fontSize: 14,
              fontWeight: isHighlighted ? FontWeight.bold : FontWeight.normal,
              color: isHighlighted ? const Color(0xFFDC2626) : Colors.black87,
            ),
          ),
          Text(
            value,
            style: TextStyle(
              fontSize: 14,
              fontWeight: isHighlighted ? FontWeight.bold : FontWeight.normal,
              color: isHighlighted ? const Color(0xFFDC2626) : Colors.black87,
            ),
          ),
        ],
      ),
    );
  }
}
